sudo: false
language: scala
dist: xenial

# compiler plugin should be fully cross-versioned. e.g.
# - https://github.com/ghik/silencer/issues/31
# - https://github.com/typelevel/kind-projector/issues/15
#
# add more scala versions when found binary and/or source incompatibilities in scala-compiler
scala:
  - 2.11.12
  - 2.12.8
  - 2.12.9
  - 2.12.11
  - 2.13.0
  - 2.13.1
jdk:
  - openjdk8
matrix:
  include:
    - scala: 2.12.11
      jdk: openjdk11
    - scala: scripted-test
      jdk: openjdk8
      env: SCRIPT=";+ core/publishLocal;+ sbt-plugin/scripted"
      script:
      - sbt "${SCRIPT}"
    - os: windows
      language: bash
      env: JDK="adopt@1.8.0-222"
      before_script:
      - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
      - source .install-jdk-travis.sh
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/0ee2dae2eba72efb4a464a5ad255e348696ecda7/sbt && chmod +x ./sbt
      script:
      - ./sbt test "+ core/publishLocal" "+ sbt-plugin/scripted"
script: sbt "++${TRAVIS_SCALA_VERSION} -v" compile test
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
