on:
  push:
  pull_request:
jobs:
  benchmark:
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        include:
          - index: 0
          - index: 1
          - index: 2
          - index: 3
          - index: 4
          - index: 5
          - index: 6
          - index: 7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
    - uses: actions/checkout@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt
           -v
           -Dbenchmark_total=8
           -Dbenchmark_index=${{ matrix.index }}
           "benchmark/Jmh/run -i 5 -wi 5 -f1 -t1"
           collectBenchmarkLog
